Deleted classes that were similar + updated composer.json
php-etl/magento2-flow pull request #1
Opened 2022-09-01 15:40 UTC by sebprt

2022-09-06 12:15 UTC, gplanchat requested changes

2022-09-06 12:15 UTC, gplanchat commented on composer.json
> +        "php-http/guzzle7-adapter": "^1.0",
Tu ne devrais pas avoir `php-http/guzzle7-adapter`, mais plutôt [`psr/http-client-implementation`](https://packagist.org/providers/psr/http-client-implementation)

2022-09-06 12:15 UTC, gplanchat commented on src/OrderExtractor.php
> +        return new AcceptanceResultBucket(...$response->getItems());
Tu ne gères pas le cas où la réponse ne réussit pas.

2022-09-06 12:15 UTC, gplanchat commented on src/ProductExtractor.php
> +        return new AcceptanceResultBucket(...$response->getItems());
Tu ne gères pas le cas où la réponse ne réussit pas.

2022-09-07 07:16 UTC, sebprt commented on composer.json
> +        "php-http/guzzle7-adapter": "^1.0",
Je n'ai pas du tout besoin de ce package dans le projet. Je l'ai supprimé.

2022-09-07 08:15 UTC, sebprt commented on src/OrderExtractor.php
> +        return new AcceptanceResultBucket(...$response->getItems());
J'ai mis à jour cette partie du code dans le cas ou j'ai un object `ErrorResponse` qui est renvoyé

2022-09-07 08:15 UTC, sebprt commented on src/ProductExtractor.php
> +        return new AcceptanceResultBucket(...$response->getItems());
J'ai mis à jour cette partie du code dans le cas ou j'ai un object `ErrorResponse` qui est renvoyé

2022-09-16 08:40 UTC, merged